package shama.addon;

import com.mojang.logging.LogUtils;
import meteordevelopment.meteorclient.addons.MeteorAddon;
import meteordevelopment.meteorclient.systems.hud.Hud;
import meteordevelopment.meteorclient.systems.hud.HudGroup;
import meteordevelopment.meteorclient.systems.modules.Category;
import meteordevelopment.meteorclient.systems.modules.Modules;
import net.minecraft.item.Items;
import org.slf4j.Logger;

import shama.addon.modules.BlockEntityFinder;
import shama.addon.modules.Autoer;
import shama.addon.modules.ChunkFinder;
import shama.addon.modules.Miner;
import shama.addon.modules.FastBow;
import shama.addon.modules.FakeVisuals;
import shama.addon.modules.FindLog;
import shama.addon.modules.Flight;
import shama.addon.modules.ForceCommands;
import shama.addon.modules.Freecam;
import shama.addon.modules.Godmode;
import shama.addon.modules.InstantMine;
import shama.addon.modules.HostileEsp;
import shama.addon.modules.Invisibility;
import shama.addon.modules.NbtAdder;
import shama.addon.modules.NoBreakDelay;
import shama.addon.modules.NoCooldown;
import shama.addon.modules.Noclip;
import shama.addon.modules.OreSim;
import shama.addon.modules.OreSpotter;
import shama.addon.modules.SnapTap;
import shama.addon.modules.StrongholdFinder;
import shama.addon.modules.RareFinder;
import shama.addon.modules.RtpFinder;
import shama.addon.modules.PingSpoofer;
import shama.addon.modules.ReachPlus;
import shama.addon.modules.Speed;
import shama.addon.modules.TunnelFinder;
import shama.addon.modules.OceanMonumentFinder;
import shama.addon.modules.HomeUtils;
import shama.addon.modules.ElytraFly;
import shama.addon.modules.Jumps;
import shama.addon.modules.FastClimb;
import shama.addon.modules.ClickTP;
import shama.addon.modules.TridentBoost;
import shama.addon.modules.SchematicBuilder;
import shama.addon.modules.SearchMap;
import shama.addon.modules.SignalScanner;
import shama.addon.modules.LogoutSpots;
import shama.addon.modules.StaffDetector;
import shama.addon.modules.RegionMapper;
import shama.addon.modules.MovementExtras;
import shama.addon.modules.AnchorAura;
import shama.addon.modules.CrystalAura;
import shama.addon.modules.CrystalOptim;
import shama.addon.modules.AutoWasp;
import shama.addon.modules.SelfDefense;
import shama.addon.modules.AutoCity;
import shama.addon.modules.AnomalyScan;
import shama.addon.modules.AntiAntiEsp;
import shama.addon.modules.AutoLog;
import shama.addon.modules.HideChat;
import shama.addon.modules.Swarm;
import shama.addon.modules.VoiceChatSniffer;
import shama.addon.modules.BowAimbot;
import shama.addon.modules.AttributeSwap;
import shama.addon.modules.CombatMacros;
import shama.addon.modules.Bypass;
import shama.addon.modules.PacketLogger;
import shama.addon.modules.WorldExtras;
import shama.addon.modules.ChatExtras;
import shama.addon.modules.Notifiers;
import shama.addon.modules.CombatExtras;
import shama.addon.modules.BaseDetector;
import shama.addon.modules.AutoSign;
import shama.addon.modules.BookBot;
import shama.addon.modules.PortalInv;
import shama.addon.modules.SwingSpeed;
import shama.addon.modules.LagDetector;
import shama.addon.modules.PlayerDetector;
import shama.addon.modules.ActiveChunkDetector;
import shama.addon.modules.DeepActivity;
import shama.addon.modules.BlockLightEsp;
import shama.addon.modules.AntiAfk;
import shama.addon.modules.ReverseStep;
import shama.addon.modules.TimeChanger;
import shama.addon.modules.Trail;
import shama.addon.modules.ItemHighlight;
import shama.addon.modules.HitParticles;
import shama.addon.modules.BreakIndicators;
import shama.addon.modules.CameraTweaks;
import shama.addon.modules.GeodeFinder;
import shama.addon.modules.HoleFinder;
import shama.addon.modules.HopperDebug;
import shama.addon.modules.HiddenPlayerDetect;
import shama.addon.modules.RenderDistanceBypass;
import shama.addon.modules.ChunkLoader;
import shama.addon.modules.ChunkReloader;
import shama.addon.modules.RegionMapModule;
import shama.addon.modules.ParticleEsp;
import shama.addon.modules.SpawnClusterFinder;
import shama.addon.modules.SpawnerFinder;
import shama.addon.modules.SusChunkFinder;
import shama.addon.modules.Timer;
import shama.addon.modules.Wallbang;
import shama.addon.modules.YLevelSpoofer;
import shama.addon.commands.NbtCommand;
import shama.addon.commands.BnbtCommand;
import meteordevelopment.meteorclient.commands.Commands;

public class ShamaAddon extends MeteorAddon {
    public static final Logger LOG = LogUtils.getLogger();

    // Custom category so all Shama modules group together in Meteor's GUI.
    /** Original Shama modules — everything built for Shama from scratch, including any that later absorbed a merged mode/idea from the gift batch. */
    public static final Category HUNT = new Category("Shama Hunt", Items.SPYGLASS.getDefaultStack());
    public static final Category COMBAT = new Category("Shama Combat", Items.NETHERITE_SWORD.getDefaultStack());
    public static final Category MOVEMENT = new Category("Shama Movement", Items.FEATHER.getDefaultStack());
    public static final Category PLAYER = new Category("Shama Player", Items.DIAMOND_PICKAXE.getDefaultStack());
    public static final Category MISC = new Category("Shama Misc", Items.NETHER_STAR.getDefaultStack());
    public static final HudGroup HUD_GROUP = new HudGroup("Shama");

    @Override
    public void onRegisterCategories() {
        Modules.registerCategory(HUNT);
        Modules.registerCategory(COMBAT);
        Modules.registerCategory(MOVEMENT);
        Modules.registerCategory(PLAYER);
        Modules.registerCategory(MISC);
    }

    @Override
    public void onInitialize() {
        LOG.info("Initializing Shama addon");

        Modules.get().add(new BlockEntityFinder());
        Modules.get().add(new ChunkFinder());
        Modules.get().add(new Miner());
        Modules.get().add(new Autoer());
        Modules.get().add(new HostileEsp());
        Modules.get().add(new YLevelSpoofer());
        Modules.get().add(new PingSpoofer());
        Modules.get().add(new FakeVisuals());
        Modules.get().add(new FindLog());
        Modules.get().add(new Flight());
        Modules.get().add(new FastBow());
        Modules.get().add(new Godmode());
        Modules.get().add(new NoCooldown());
        Modules.get().add(new InstantMine());
        Modules.get().add(new NoBreakDelay());
        Modules.get().add(new Noclip());
        Modules.get().add(new OreSim());
        Modules.get().add(new ReachPlus());
        Modules.get().add(new Wallbang());
        Modules.get().add(new ForceCommands());
        Modules.get().add(new Freecam());
        Modules.get().add(new Speed());
        Modules.get().add(new SusChunkFinder());
        Modules.get().add(new SpawnerFinder());
        Modules.get().add(new SpawnClusterFinder());
        Modules.get().add(new TunnelFinder());
        Modules.get().add(new OceanMonumentFinder());
        Modules.get().add(new HomeUtils());
        Modules.get().add(new ElytraFly());
        Modules.get().add(new Jumps());
        Modules.get().add(new FastClimb());
        Modules.get().add(new ClickTP());
        Modules.get().add(new TridentBoost());
        Modules.get().add(new SchematicBuilder());
        Modules.get().add(new SearchMap());
        Modules.get().add(new SignalScanner());
        Modules.get().add(new LogoutSpots());
        Modules.get().add(new StaffDetector());
        Modules.get().add(new RegionMapper());
        Modules.get().add(new MovementExtras());
        Modules.get().add(new AnchorAura());
        Modules.get().add(new CrystalAura());
        Modules.get().add(new CrystalOptim());
        Modules.get().add(new ParticleEsp());
        Modules.get().add(new RegionMapModule());
        Modules.get().add(new ChunkLoader());
        Modules.get().add(new ChunkReloader());
        Modules.get().add(new RenderDistanceBypass());
        Modules.get().add(new HiddenPlayerDetect());
        Modules.get().add(new GeodeFinder());
        Modules.get().add(new HoleFinder());
        Modules.get().add(new HopperDebug());
        Modules.get().add(new CameraTweaks());
        Modules.get().add(new BreakIndicators());
        Modules.get().add(new HitParticles());
        Modules.get().add(new ItemHighlight());
        Modules.get().add(new Trail());
        Modules.get().add(new TimeChanger());
        Modules.get().add(new ReverseStep());
        Modules.get().add(new AntiAfk());
        Modules.get().add(new BlockLightEsp());
        Modules.get().add(new DeepActivity());
        Modules.get().add(new PlayerDetector());
        Modules.get().add(new ActiveChunkDetector());
        Modules.get().add(new LagDetector());
        Modules.get().add(new PortalInv());
        Modules.get().add(new SwingSpeed());
        Modules.get().add(new AutoSign());
        Modules.get().add(new BookBot());
        Modules.get().add(new Bypass());
        Modules.get().add(new PacketLogger());
        Modules.get().add(new WorldExtras());
        Modules.get().add(new ChatExtras());
        Modules.get().add(new Notifiers());
        Modules.get().add(new CombatExtras());
        Modules.get().add(new BaseDetector());
        Modules.get().add(new VoiceChatSniffer());
        Modules.get().add(new BowAimbot());
        Modules.get().add(new AttributeSwap());
        Modules.get().add(new CombatMacros());
        Modules.get().add(new AutoWasp());
        Modules.get().add(new SelfDefense());
        Modules.get().add(new AutoCity());
        Modules.get().add(new AnomalyScan());
        Modules.get().add(new AntiAntiEsp());
        Modules.get().add(new AutoLog());
        Modules.get().add(new HideChat());
        Modules.get().add(new Swarm());

        Hud.get().register(shama.addon.hud.RadarHud.INFO);
        Hud.get().register(shama.addon.hud.LightHud.INFO);
        Hud.get().register(shama.addon.hud.RegionHud.INFO);
        Hud.get().register(shama.addon.hud.BaseRadarHud.INFO);
        Modules.get().add(new Invisibility());
        Modules.get().add(new OreSpotter());
        Modules.get().add(new SnapTap());
        Modules.get().add(new StrongholdFinder());
        Modules.get().add(new RareFinder());
        Modules.get().add(new RtpFinder());
        Modules.get().add(new NbtAdder());
        Modules.get().add(new Timer());

        Commands.add(new NbtCommand());
        Commands.add(new BnbtCommand());
    }

    @Override
    public String getPackage() {
        return "shama.addon";
    }
}
